name: Interactive Art / Creative Code
baseurl: /ARTTECH-3135
url: https://saic-ats.github.io/ARTTECH-3135
description: ARTTECH 3135 / 5135
timezone: America/Chicago
plugins:
    - jekyll-sitemap
highlighter: rouge
